from __future__ import annotations

import os

SERVICE_NAME = "notification-service"
SERVICE_VERSION = "0.1.0"

EVENT_STARTUP_COMPLETE = "startup_complete"
EVENT_CONSUMER_ERROR = "consumer_error"
EVENT_CONSUMER_STARTED = "consumer_started"

NOTIFICATION_DB_ENV = "NOTIFICATION_DB"

RABBIT_URL_ENV = "RABBIT_URL"
RABBIT_URL_DEFAULT = "amqp://guest:guest@rabbitmq:5672/"
RABBIT_URL = os.getenv(RABBIT_URL_ENV, RABBIT_URL_DEFAULT)

DOMAIN_EVENTS_EXCHANGE_ENV = "DOMAIN_EVENTS_EXCHANGE"
DOMAIN_EVENTS_EXCHANGE_DEFAULT = "domain_events"
EXCHANGE_NAME = os.getenv(DOMAIN_EVENTS_EXCHANGE_ENV, DOMAIN_EVENTS_EXCHANGE_DEFAULT)

NOTIFICATION_QUEUE_ENV = "NOTIFICATION_QUEUE"
NOTIFICATION_QUEUE_DEFAULT = "notification_service_events"
QUEUE_NAME = os.getenv(NOTIFICATION_QUEUE_ENV, NOTIFICATION_QUEUE_DEFAULT)

RETRY_QUEUE_SUFFIX = "_retry"
DLQ_QUEUE_SUFFIX = "_dlq"
RETRY_QUEUE = f"{QUEUE_NAME}{RETRY_QUEUE_SUFFIX}"
DLQ_QUEUE = f"{QUEUE_NAME}{DLQ_QUEUE_SUFFIX}"

DEFAULT_RETRY_DELAY_MS = 5000
DEFAULT_MAX_RETRIES = 3
DEFAULT_PREFETCH = 100
CONSUMER_RECONNECT_WAIT_SECONDS = 5

HEADER_X_USER_EMAIL = "X-User-Email"
HEADER_X_USER_ROLES = "X-User-Roles"

HEALTH_OK_KEY = "ok"
HEALTH_SERVICE_KEY = "service"

ERROR_MISSING_USER_EMAIL_HEADER = "Missing X-User-Email header"