from shared.shared.schemas.auth import (
    Register,
    Login,
    TokenPairResponse,
    TokenResponse,
    RefreshRequest,
    LogoutRequest,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    EmailVerifyRequest,
    EmailVerifyConfirmRequest,
    AuthActionResponse,
    AuthUserResponse,
    UpdateAuthUserPassword,
    UpdateAuthUserRoles,
    UpdateAuthUser,
)