from __future__ import annotations

DEFAULT_SKILLS_CATALOG: dict[str, list[str]] = {
    "construction_structural": [
        "carpentry",
        "furniture_assembly",
        "cabinet_installation",
        "drywall_installation",
        "drywall_repair",
        "framing",
        "deck_building_repair",
        "fence_installation_repair",
        "stair_repair",
        "door_installation",
        "window_installation",
    ],
    "finishing_interior": [
        "interior_painting",
        "exterior_painting",
        "wallpaper_installation_removal",
        "tile_installation",
        "tile_repair",
        "caulking_sealing",
        "trim_molding_installation",
        "flooring_installation",
        "grout_repair",
        "plaster_repair",
    ],
    "plumbing": [
        "faucet_installation_repair",
        "sink_installation",
        "toilet_installation_repair",
        "showerhead_installation",
        "leak_detection_repair",
        "pipe_replacement",
        "drain_unclogging",
        "garbage_disposal_installation",
        "dishwasher_hookup",
    ],
    "electrical_basic": [
        "light_fixture_installation",
        "ceiling_fan_installation",
        "switch_outlet_replacement",
        "smart_switch_installation",
        "doorbell_installation",
        "led_lighting_upgrades",
        "basic_electrical_troubleshooting",
    ],
    "outdoor_exterior": [
        "gutter_cleaning_repair",
        "pressure_washing",
        "shed_assembly",
        "patio_installation",
        "fence_painting_staining",
        "weatherproofing",
        "minor_roof_repairs",
        "landscaping_maintenance",
        "irrigation_repair",
    ],
    "furniture_fixtures": [
        "furniture_repair",
        "flatpack_assembly",
        "shelf_installation",
        "closet_system_installation",
        "tv_wall_mounting",
        "curtain_rod_installation",
        "mirror_mounting",
        "picture_hanging",
    ],
    "maintenance_repair": [
        "general_home_maintenance",
        "lock_replacement_repair",
        "door_alignment_hinge_repair",
        "window_screen_repair",
        "weatherstripping_installation",
        "appliance_installation",
        "small_appliance_repair",
    ],
    "modern_handyman": [
        "smart_home_device_installation",
        "security_camera_installation",
        "wifi_doorbell_installation",
        "ev_charger_installation",
        "solar_light_installation",
    ],
}