from __future__ import annotations

import os

from ..domain.constants import MatchEventType

SERVICE_NAME = "match-service"
SERVICE_VERSION = "0.1.0"

QUEUE_NAME = "match_service_domain_events"
RETRY_QUEUE_SUFFIX = "_retry"
DLQ_QUEUE_SUFFIX = "_dlq"
RETRY_QUEUE = f"{QUEUE_NAME}{RETRY_QUEUE_SUFFIX}"
DLQ_QUEUE = f"{QUEUE_NAME}{DLQ_QUEUE_SUFFIX}"

ROUTING_KEYS = (
    MatchEventType.AVAILABILITY_UPDATED,
    MatchEventType.HANDYMAN_CREATED,
    MatchEventType.HANDYMAN_LOCATION_UPDATED,
    MatchEventType.HANDYMAN_UPDATED,
    MatchEventType.HANDYMAN_DELETED,
)

DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY_MS = 5000
DEFAULT_PREFETCH = 50
IDEMPOTENCY_TTL_SECONDS = 3600
CONSUMER_RETRY_SECONDS = 5

REDIS_URL_ENV = "REDIS_URL"
REDIS_URL = os.getenv(REDIS_URL_ENV)
REDIS_URL_MISSING_ERROR = f"{REDIS_URL_ENV} environment variable is not set"

MATCH_GRID_DEG_ENV = "MATCH_GRID_DEG"
MATCH_GRID_DEG_DEFAULT = "0.05"
GRID_DEG = float(os.getenv(MATCH_GRID_DEG_ENV) or MATCH_GRID_DEG_DEFAULT)

MATCH_TIME_BUCKET_SECONDS_ENV = "MATCH_TIME_BUCKET_SECONDS"
MATCH_TIME_BUCKET_SECONDS_DEFAULT = "900"
TIME_BUCKET_SECONDS = int(os.getenv(MATCH_TIME_BUCKET_SECONDS_ENV) or MATCH_TIME_BUCKET_SECONDS_DEFAULT)

HANDYMAN_SERVICE_URL_ENV = "HANDYMAN_SERVICE_URL"
HANDYMAN_SERVICE_URL_DEFAULT = "http://handyman-service:8000"
HANDYMAN_SERVICE_URL = os.getenv(HANDYMAN_SERVICE_URL_ENV, HANDYMAN_SERVICE_URL_DEFAULT)

AVAILABILITY_SERVICE_URL_ENV = "AVAILABILITY_SERVICE_URL"
AVAILABILITY_SERVICE_URL_DEFAULT = "http://availability-service:8000"
AVAILABILITY_SERVICE_URL = os.getenv(AVAILABILITY_SERVICE_URL_ENV, AVAILABILITY_SERVICE_URL_DEFAULT)

BOOKING_SERVICE_URL_ENV = "BOOKING_SERVICE_URL"
BOOKING_SERVICE_URL_DEFAULT = "http://booking-service:8000"
BOOKING_SERVICE_URL = os.getenv(BOOKING_SERVICE_URL_ENV, BOOKING_SERVICE_URL_DEFAULT)

HANDYMEN_ENDPOINT = "/handymen"
AVAILABILITY_ENDPOINT_PREFIX = "/availability"
BOOKING_COMPLETED_COUNTS_ENDPOINT = "/bookings/completed-counts"

HTTP_TIMEOUT = 2.0
CACHE_TTL_STRICT_SECONDS = 60
CACHE_TTL_DEGRADED_SECONDS = 15
CACHE_INDEX_TTL_BUFFER_SECONDS = 30

SERVICE_LOG_PREFIX = f"[{SERVICE_NAME}]"